name: MP_ga

on:
  workflow_dispatch:
    
jobs: 
  MP_ga:
    name: MP_ga job
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Hello world"
      - run: ls -lah
      - run: whoami
      - run: df -h
      - uses: actions/checkout@v2
      - run: ls -lah
